### ISSUE TITLE
Figure out how to host a website with a folium map using Flask

### ISSUE THREAD

**Issue by zpleunis** [marlena6/telescopes-indigenous-lands#2]

**Comment by zpleunis** [comment]
https://towardsdatascience.com/your-cool-folium-maps-on-the-web-313f9d1a6bcd

https://medium.com/analytics-vidhya/data-visualization-deploying-an-interactive-map-as-a-web-app-with-heroku-51a323029e4

https://stackoverflow.com/questions/37379374/insert-the-folium-maps-into-the-jinja-template/60031784#60031784

**Comment by taylorkutra** [comment]
Figured this out using jupyter nbconvert. See [here](https://www.geeksforgeeks.org/publish-jupiter-notebook-file-as-web-app/) for tutorial.
